# Configurações de conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_piscinas
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# A mágica do Hibernate: Cria e atualiza as tabelas automaticamente no banco
spring.jpa.hibernate.ddl-auto=update

# Mostra no console do VS Code os comandos SQL que o Java está executando por baixo dos panos
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true